name: dart_angular_ngfor_ngcontrol_bug
description: Example for bug https://github.com/dart-lang/angular2/issues/164
version: 0.0.1
environment:
  sdk: '1.20.1'
dependencies:
  analyzer: any
  angular2: ^2.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
